[package]
name = "alethe-proof-checker-cli"
version = "0.1.0"
edition = "2021"
rust-version = "1.59"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "alethe-proof-checker"
path = "src/main.rs"

[dependencies]
alethe-proof-checker = { path = "../alethe-proof-checker" }
ahash = "0.7.4"
clap = { version = "3.1.6", features = ["derive"] }
const_format = "0.2.22"
crossbeam = "0.8"
log = { version = "0.4.14", features = ["std"] }
ansi_term = "0.11"
git-version = "0.3.5"
